name: Test and Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15

      - name: Check out code
        uses: actions/checkout@v2

      - name: goimports
        run: go get golang.org/x/tools/cmd/goimports && goimports

      - name: go vet
        run: go vet ./...
    
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.31
    
      - name: go test
        run: make test-ci
      
      - name: upload codecov
        run: bash <(curl -s https://codecov.io/bash)
      
      - name: Build binaries
        run: make build

      - name: Test
        run: make test
